import Head from 'next/head'

export default function Titulo(){
    return(
        <Head>
        <title>Baú de Doce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logomarca.ico"/>
      </Head>
    )
}